import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { POSModel } from '../components/models/pos.model';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  cardColors: string[] = [
    '#E3F2FD',
    '#FFF9E1',
    '#ffebf5',
    '#E8F5E9',
    '#ffe0e0',
    '#E0F7FA',
    '#FFFDE7',
    '#F3E5F5',
  ];

  constructor() {}

  loadData(): Observable<POSModel[]> {
    return of([
      {
        waiter: {
          name: 'Leslie K.',
          selected: true,
        },
        tables: [
          {
            tableNumber: 1,
            selected: true,
            menuItems: [
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fish and Chips',
                price: 50,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Chicken',
                price: 45,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fillet Steak',
                price: 85,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Beefsteak',
                price: 81,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Beef',
                price: 75,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Buffalo Wings',
                price: 78,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Lobster',
                price: 120,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Braaibroodjies',
                price: 25,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
            ],
          },
          {
            tableNumber: 2,
            selected: false,
            menuItems: [
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fish and Chips',
                price: 50,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Chicken',
                price: 45,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fillet Steak',
                price: 85,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Beefsteak',
                price: 81,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Beef',
                price: 75,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Buffalo Wings',
                price: 78,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Lobster',
                price: 120,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Braaibroodjies',
                price: 25,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
            ],
          },
          {
            tableNumber: 3,
            selected: false,
            menuItems: [
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fish and Chips',
                price: 50,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Chicken',
                price: 45,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fillet Steak',
                price: 85,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Beefsteak',
                price: 81,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Beef',
                price: 75,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Buffalo Wings',
                price: 78,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Lobster',
                price: 120,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Braaibroodjies',
                price: 25,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
            ],
          },
        ],
      },
      {
        waiter: {
          name: 'Cameron W.',
          selected: false,
        },
        tables: [
          {
            tableNumber: 4,
            selected: true,
            menuItems: [
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fish and Chips',
                price: 50,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Chicken',
                price: 45,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fillet Steak',
                price: 85,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Beefsteak',
                price: 81,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Beef',
                price: 75,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Buffalo Wings',
                price: 78,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Lobster',
                price: 120,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Braaibroodjies',
                price: 25,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
            ],
          },
          {
            tableNumber: 5,
            selected: false,
            menuItems: [
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fish and Chips',
                price: 50,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Chicken',
                price: 45,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fillet Steak',
                price: 85,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Beefsteak',
                price: 81,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Beef',
                price: 75,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Buffalo Wings',
                price: 78,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Lobster',
                price: 120,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Braaibroodjies',
                price: 25,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
            ],
          },
          {
            tableNumber: 6,
            selected: false,
            menuItems: [
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fish and Chips',
                price: 50,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Chicken',
                price: 45,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fillet Steak',
                price: 85,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Beefsteak',
                price: 81,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Beef',
                price: 75,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Buffalo Wings',
                price: 78,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Lobster',
                price: 120,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Braaibroodjies',
                price: 25,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
            ],
          },
        ],
      },
      {
        waiter: {
          name: 'Jacob J.',
          selected: false,
        },
        tables: [
          {
            tableNumber: 7,
            selected: true,
            menuItems: [
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fish and Chips',
                price: 50,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Chicken',
                price: 45,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fillet Steak',
                price: 85,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Beefsteak',
                price: 81,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Beef',
                price: 75,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Buffalo Wings',
                price: 78,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Lobster',
                price: 120,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Braaibroodjies',
                price: 25,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
            ],
          },
          {
            tableNumber: 8,
            selected: false,
            menuItems: [
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fish and Chips',
                price: 50,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Chicken',
                price: 45,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fillet Steak',
                price: 85,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Beefsteak',
                price: 81,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Beef',
                price: 75,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Buffalo Wings',
                price: 78,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Lobster',
                price: 120,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Braaibroodjies',
                price: 25,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
            ],
          },
          {
            tableNumber: 9,
            selected: false,
            menuItems: [
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fish and Chips',
                price: 50,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Chicken',
                price: 45,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fillet Steak',
                price: 85,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Beefsteak',
                price: 81,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Beef',
                price: 75,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Buffalo Wings',
                price: 78,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Lobster',
                price: 120,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Braaibroodjies',
                price: 25,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
            ],
          },
        ],
      },
      {
        waiter: {
          name: 'Nel J.',
          selected: false,
        },
        tables: [
          {
            tableNumber: 10,
            selected: true,
            menuItems: [
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fish and Chips',
                price: 50,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Chicken',
                price: 45,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fillet Steak',
                price: 85,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Beefsteak',
                price: 81,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Beef',
                price: 75,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Buffalo Wings',
                price: 78,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Lobster',
                price: 120,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Braaibroodjies',
                price: 25,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
            ],
          },
          {
            tableNumber: 11,
            selected: false,
            menuItems: [
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fish and Chips',
                price: 50,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Chicken',
                price: 45,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fillet Steak',
                price: 85,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Beefsteak',
                price: 81,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Beef',
                price: 75,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Buffalo Wings',
                price: 78,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Lobster',
                price: 120,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Braaibroodjies',
                price: 25,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
            ],
          },
          {
            tableNumber: 12,
            selected: false,
            menuItems: [
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fish and Chips',
                price: 50,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Chicken',
                price: 45,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Fillet Steak',
                price: 85,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Beefsteak',
                price: 81,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Roast Beef',
                price: 75,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Buffalo Wings',
                price: 78,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Lobster',
                price: 120,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
              {
                breadcrumb: ['Orders', 'Kitchen'],
                title: 'Braaibroodjies',
                price: 25,
                quantity: 0,
                total: 0,
                selected: false,
                icon: 'free_breakfast',
              },
            ],
          },
        ],
      },
    ]);
  }
}
